---
  3cx_wallboard_host: IP or FQDN of 3CX Phone Server
  3cx_wallboard_port: "80"
  3cx_websocket_port: "4516"
  username: "user extension that has wallboard access"
  password: password
  queue: "QueueID NOT Queue Name, Can be found in the Wallboard's cookie data"
  loginbutton: "Log In"
  mysql_host: hostname of mysql server
  mysql_user: mysql username
  mysql_pass: mysql password
  mysql_db: mysql db to write to
